### ISSUE TITLE
Google Api key is required

### ISSUE THREAD

**Issue by olajhidey** [alaouy/Youtube#100]
Hello am having a bit of an issue i added my api key to my laravel project both on the .env file and the config/youtube.php file but it keeps on displaying the Exception Google API key required.

**Comment by Seaclick** [comment]
Same issue for me. Sounds like the referer is not sent to the API.

**Comment by olajhidey** [comment]
i already figured it out you have to add the api key to the .env file in laravel before you publish the config.. It should work fine

**Comment by imsidz** [comment]
after set key in your .env use`php artisan config:cache` it should work fine

**Comment by alaouy** [comment]
Guys any PRs in this regard are welcome (y)
