### ISSUE TITLE
Error 400 Bad Request : keyInvalid

### ISSUE THREAD

**Issue by badrshs** [alaouy/Youtube#101]
Hi , 
everything was fine , the application is running since 2 years ago without problem , 
today I have tried to use a feature in my project which related to **alaouy/Youtube,**

but I got an error , I dont know why 
```
(1/1) Exception
Error 400 Bad Request : keyInvalid

in Youtube.php line 546
--
at Youtube->decodeSingle('{ "error": { "errors": [ { "domain": "usageLimits", "reason": "keyInvalid", "message": "Bad Request" } ], "code": 400, "message": "Bad Request" }}')in Youtube.php line 370
at Youtube->getPlaylistById('PLMYF6NkLrdN9JJPTR0ksQcT3uumyco7UG')in Facade.php line 221
at Facade::__callStatic('getPlaylistById', array('PLMYF6NkLrdN9JJPTR0ksQcT3uumyco7UG'))in AddNewCourseController.php line 55
at AddNewCourseController->add()

```
 
I didnt touch the key in my application , even I didnt change any code since long time ago except `( composer update )`
any help please ? what is going on ?

**Comment by badrshs** [comment]
I got the solution from another issue and the problem is solved 
the solution is changing `config/youtube.php`  from "KEY" to "key" then

`"php artisan config:cache".
`

**Comment by alaouy** [comment]
@badrshs thanks for reposting the solution here, much appreciated.
