### ISSUE TITLE
Can't guess how  searchChannelVideo search

### ISSUE THREAD

**Issue by yagogak** [alaouy/Youtube#105]
Hi, 
i'm wondering on which terms searchChannelVideos perform the search. It seems that terms in the video title are not beeing searched.

ex: on the channel a video with name "this is a test"
a test with searchChannelVideos( "test", 'channel_id', 10 ) wont return anything.

Any idea ?

**Comment by alaouy** [comment]
@yagogak This is the documentation of the endpoint used in the search feature : https://developers.google.com/youtube/v3/docs/search/list
I can't tell extactely what is the issue in your case but as far as I know the API uses the same search feature that they have on the website, so my best guess is that you try the same search query in the channel page on youtube.com and see if it will return any results.
