### ISSUE TITLE
tried to get all chanel videos by searchAdvanced. Got no more than ~ 550 pieces. 

### ISSUE THREAD

**Issue by hubsmall** [alaouy/Youtube#110]
Hi! Thanks for a good tool. But got some problem. Using code like this 
```php
$params = array(
    'type'          => 'video',
    'part'          => 'id', 
    'channelId' => 'UCZZXigZOJtStkv9_1Oks-sw',
    'maxResults'    => 50
);
$tmp        = Youtube::searchAdvanced($params, true);
$videos     = $tmp['results'];
$pageToken  = $tmp['info']['nextPageToken'];
$params['pageToken'] = $pageToken;
while ($pageToken != null) { 
    $tmp       = Youtube::searchAdvanced($params, true);
    $pageToken = $tmp['info']['nextPageToken'];
    $params['pageToken'] = $pageToken;
    if($tmp['results'])
    $videos = array_merge ($videos, $tmp['results']);                   
}
```

get not ALL videos from the chanel but only arond 550. Problem in quota? Is there any way to list ALL any chanels videos? After hitting next page token of number 10 or 11 "results" massive returns false, though next page token  still has value. Will appreciate any help. Thanks.

**Comment by alaouy** [comment]
@hubsmall Sorry for the delayed response, did you manage to solve your issue ?

**Comment by hubsmall** [comment]
No. Left as it is. But there is some noise that you can add date intervals to list all videos from the earliest to the latest this way.

**Comment by bzx** [comment]
@hubsmall wanna share that part of your code? :) also +1 on fixing this.

**Comment by MSBIZ** [comment]
Hi @hubsmall 

Can you send part of your code with date intervals please ?

@alaouy maybe you can help me ? because i can get have 550 pieces, not more. 

Thanks guys

**Comment by oroalej** [comment]
Why is the nextPageToken for the searchAdvanced API is always null?

**Comment by oroalej** [comment]
Is this the package limitation or Youtube APIs?

**Comment by aronquiray** [comment]
I think it's youtube's api limitation. I get always 
Error 403 The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>. : quotaExceeded 
just listing 40 videos of a channel! ._.
