### ISSUE TITLE
I Have Curl Error 

### ISSUE THREAD

**Issue by m-farah** [alaouy/Youtube#111]
when I trying to print anything from this package I'm getting this error:
Curl Error: SSL certificate problem: unable to get local issuer certificate
I'm tried to solve this by many solutions but still getting the same error

**Comment by m-farah** [comment]
I tried that solution but I still get same Error

**Comment by alaouy** [comment]
As this is not a package issue, you can double check with this https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

**Comment by m-farah** [comment]
I Also Tried that before posting here but nothing changed

**Comment by alaouy** [comment]
My recommendation is to use a linux machine instead or uninstall wamp and start from the begining with a clean slate.

**Comment by m-farah** [comment]
thanks, I fixed it by using Xampp server
