### ISSUE TITLE
How to get category list?

### ISSUE THREAD

**Issue by arjayads** [alaouy/Youtube#112]
Returns a list of categories that can be associated with YouTube videos:
https://developers.google.com/youtube/v3/docs/videoCategories/list

**Comment by alaouy** [comment]
@arjayads you can retrieve the categories like this : 
```php
$categories = Youtube::getCategories('US', ['snippet']);
```
https://github.com/alaouy/Youtube/blob/master/src/Youtube.php#L72

**Comment by arjayads** [comment]
Thank you very much
