### ISSUE TITLE
How to discover channels category?

### ISSUE THREAD

**Issue by markoman78** [alaouy/Youtube#117]
Any idea how to discover channel category? I believe uploader can't set channel category but Youtube will assign one based of videos category.

**Comment by alaouy** [comment]
@markoman78 You can get the topic categories `topicDetails.topicCategories[]` assigned to that channel, but you can't get the related channels (assigned by youtube) which is different from the featured channels set by the channel owner.
More here https://developers.google.com/youtube/v3/docs/channels

**Comment by markoman78** [comment]
Ok thanks.
