### ISSUE TITLE
is there a way to display private live stream videos?

### ISSUE THREAD

**Issue by caturseptian** [alaouy/Youtube#122]
is there a way to display private live stream videos?

**Comment by alaouy** [comment]
@caturseptian This package only covers the Youtube Data API, in order to query live streams you need to use the LiveBroadcast API https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list

**Comment by caturseptian** [comment]
@alaouy okey, but is there a way to get a live broadcast list without having to do ask permissions and authorization access step?

**Comment by alaouy** [comment]
@caturseptian The documentation states that you need authorization tokens to access this 
You can try it here https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list#try-it
