### ISSUE TITLE
Retrieve YouTube Account ID

### ISSUE THREAD

**Issue by mihailogordon** [alaouy/Youtube#124]
Hello, 

First of all, thank you for the awesome API.

I am not reporting issue or bug, I just wanted to know if I can retrieve YouTube account ID using user's mail? I have users registered using mail, and I would like to obtain info from their YouTube profiles using associated mail.

Thank you in advance.

**Comment by alaouy** [comment]
@mihailogordon Hey, for privacy reasons I don't believe that this is possible using the YoutubeData API
