### ISSUE TITLE
Quota Exceeded exception

### ISSUE THREAD

**Issue by Valkyrurr** [alaouy/Youtube#129]
Hi. Can anyone walk me through how to handle said error? Documentation can be found [here](https://developers.google.com/youtube/v3/docs/errors).

But, the problem is I can't seem to extend the `throw new \Exception($msg)` invoked by the package. Not quite sure where to start. 

EDIT: What I did was dump the contents of `$msg`, I assume I could just parse the contents of said variable and go from there? Seems hacky. But, is there a much elegant way to handle this?

**Comment by alaouy** [comment]
Since all request might be subject to encountering that exception, you can catch the message using a try catch block:
```php
try {
    $video = Youtube::getVideoInfo('.....');
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```
More of that here: https://www.php.net/manual/en/language.exceptions.php

**Comment by Valkyrurr** [comment]
I see. Thanks!

**Comment by Valkyrurr** [comment]
Hey. Back... trying to revisit this.

Whenever I try your suggestion now , the `echo 'Caught exception: ',  $e->getMessage(), "\n";` bit doesn't get executed at all. It all stops at `$video = Youtube::getVideoInfo('.....');`.

**Comment by Valkyrurr** [comment]
Nvm. My bad.
