### ISSUE TITLE
Custom part

### ISSUE THREAD

**Issue by lamoni** [alaouy/Youtube#13]
Is there a clean way to remove / overwrite the 'part' key in the requests?  Use case: I only need the ID of the video, don't need the snippet (and the snippet costs in API quota)

**Comment by alaouy** [comment]
@lamoni I completely understand your issue, but when I made this I wanted it to be as easy to use as possible and API Quotas weren't my first concern, but if you are using the search api just omit the ``` snippet ``` keyword from the ``` part ``` parameter other than that you unfortunately can't. Unless you make a pull request providing this option to override the request parameters I'll be happy to merge it ^^

**Comment by lamoni** [comment]
@alaouy Definitely understandable, thanks!  I'll throw a pull request in a bit :)

**Comment by alaouy** [comment]
@lamoni Thanks :+1:
