### ISSUE TITLE
Unrelated question, perhaps?

### ISSUE THREAD

**Issue by Valkyrurr** [alaouy/Youtube#131]
I have my quota limit currently set to 10,000. And, I have no means to increase it at the moment. I was thinking to shuffle out API keys I have (I can have multiple keys, from multiple projects, right?). Weird solution, I know. But, is this really possible? I can change YOUTUBE_API_KEY on runtime for sure, but it seems like this package is unable to know that... Any advice?

UNRELATED: Is Youtube API quota increase for free!? The internet seems to have no info about this.

**Comment by alaouy** [comment]
You can set the API key programmatically at run time using ```Youtube::setApiKey('KEY');```

**Comment by Valkyrurr** [comment]
I did not realize I can do that... hmmm. Thanks!
