### ISSUE TITLE
parseVidFromURL doesn't parse short youtube urls

### ISSUE THREAD

**Issue by mathew-rajan** [alaouy/Youtube#133]
For short Youtube links like,  https://youtu.be/oLTNtvIHJ7M doesn't parse correctly to get the video ID

**Comment by alaouy** [comment]
@mathew-rajan A PR to include this functionality would be welcome

**Comment by alaouy** [comment]
This is now supported with short links: https://github.com/alaouy/Youtube/blob/master/src/Youtube.php#L563
