### ISSUE TITLE
Catch exceptions: Exception: Error 403 Daily Limit Exceeded

### ISSUE THREAD

**Issue by vlahde** [alaouy/Youtube#135]
I am getting production.ERROR: Exception: Error 403 Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console. Is there a way to access error instead of throwing it?

`production.ERROR: Exception: Error 403 Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas? : dailyLimitExceeded in /var/www/videospace/vendor/alaouy/youtube/src/Alaouy/Youtube/Youtube.php:558
Stack trace:
#0 /var/www/videospace/vendor/alaouy/youtube/src/Alaouy/Youtube/Youtube.php(213): Alaouy\Youtube\Youtube->decodeList('{\n "error": {\n ...')
#1 /var/www/videospace/vendor/alaouy/youtube/src/Alaouy/Youtube/Youtube.php(134): Alaouy\Youtube\Youtube->searchAdvanced(Array)
#2 /var/www/videospace/bootstrap/cache/compiled.php(6468): Alaouy\Youtube\Youtube->searchVideos('"War and Rememb...')`

**Comment by alaouy** [comment]
@vlahde putting your calls inside try catch block is the solution for you.
