### ISSUE TITLE
Error 403 Access Not Configured.

### ISSUE THREAD

**Issue by ciclanoio** [alaouy/Youtube#137]
Error 403 Access Not Configured. YouTube Data API has not been used in project XXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. : accessNotConfiguredc

But the project is configured and running in another lib

**Comment by alaouy** [comment]
@ciclanoio Have you added any restrictions on the your Google Console API ?

**Comment by santutu** [comment]
Recreate  project on google cloud console.
Maybe it is bug.

**Comment by kirilkirkov** [comment]
@ciclanoio  How did you solve this problem?
The proposal of @santutu is not a solution. If i have project with compute engines ,etc. i cant delete it...
I have create key with and without restrictions but i still get same error. Do somebody know why? @alaouy ?
