### ISSUE TITLE
Too much quote usage

### ISSUE THREAD

**Issue by Nevermind23** [alaouy/Youtube#140]
Just checked and my script is sending too many queries

`$video = Youtube::getVideoInfo($videoId); // 9 queries`
`$channel = Youtube::getChannelById($video->snippet->channelId); // 9 queries`
`$relatedVideos = Youtube::getRelatedVideos($videoId); // 101 queries`

Calling those 3 functions uses approximately 120 queries, that's abnormal quantity, rate exceeds in few minutes, what could be wrong ?

**Comment by ossigeno** [comment]
Those are inline with the Google documentation:

E.g. Search: list (which getRelatedVideos is a wrapper around)
https://developers.google.com/youtube/v3/docs/search/list
Quota impact: A call to this method has a quota cost of 100 units.

**Comment by Korko** [comment]
And each getVideoInfo/getChannelById by default fetch all parts. If you want to reduce your quota usage, define the parts argument and limit to what you really need
`getVideoInfo($vId, $part = ['id', 'snippet', 'contentDetails', 'player', 'statistics', 'status'])`
`getChannelById($id, $optionalParams = [], $part = ['id', 'snippet', 'contentDetails', 'statistics', 'invideoPromotion'])`

**Comment by acidjazz** [comment]
@Nevermind23 @ossigeno @Korko FYI due to this new quota issue with youtube, I've built 
https://github.com/acidjazz/tubestrip

**Comment by Nevermind23** [comment]
> @Nevermind23 @ossigeno @Korko FYI due to this new quota issue with youtube, I've built 
> https://github.com/acidjazz/tubestrip

This is not issue, it's just the price for request. I have built similar library by myself to reduce requests, but it's using almost same amount, so it's not package's fault

**Comment by acidjazz** [comment]
@Nevermind23 Correct, I am not saying anything is wrong, just giving a solution for the quota limit issue
