### ISSUE TITLE
How to paginate videos from channelId ?

### ISSUE THREAD

**Issue by boypanjaitan16** [alaouy/Youtube#146]
In the example you just show the way to paginate from search results, but how to do it with videos from channelId ?

**Comment by Korko** [comment]
I guess what you mean by videos from channelId is
`getPlaylistItemsByPlaylistId($playlistId, $pageToken = '', $maxResults = 50, $part = ['id', 'snippet', 'contentDetails', 'status'])`?

The $pageToken is the key. First call, no pageToken, the result may contain a ['info']['nextPageToken']. You can then call the same method again with the pageToken. You will then fetch the next page of results.
