### ISSUE TITLE
Upload Video to Youtube

### ISSUE THREAD

**Issue by vsmartcode** [alaouy/Youtube#147]
I know the package does not support upload video to youtube and I find that the joedawson / youtube package supports this feature so can I use both packages together?
I see that both of our Faces are "Youtube", so does it conflict?

**Comment by Korko** [comment]
Not sure about how Laravel handles conflict in aliases auto discovery but you may be able to use both at the same time. The only limitation is that you may not use `use Youtube;` in the header but `use Alaouy\Youtube\Facades\Youtube;` and `use Dawson\Youtube\Facades\Youtube as YoutubeUpload;`
