### ISSUE TITLE
[bug] listChannelVideos returning empty items list when channel is new

### ISSUE THREAD

**Issue by ibrunotome** [alaouy/Youtube#151]
Example: `listChannelVideos('UC5p-sMbm64A8aJ586Cbm3Zw');`

The above channel is new and has one posted video.

Also, it brokes with a message "Undefined property: stdClass::$items"

I dumped the api query right before the lib interact with items and got:

![2020-06-28 17 03 37](https://user-images.githubusercontent.com/4256471/85957155-75f24780-b961-11ea-89a3-4bd05f3c160f.jpg)

**Comment by alaouy** [comment]
@ibrunotome Did you try the same query on Google's Youtube Data Explorer to check if it returns the same result?

**Comment by ibrunotome** [comment]
@alaouy Tested right now and it's working both on data explorer and in your library. But on the day that I open this issue, the channel was just created some hours before and the library wasn't finding videos, and unfortunally I didn't tested on data explorer on that day 😢
