### ISSUE TITLE
Transcript?

### ISSUE THREAD

**Issue by kylescousin** [alaouy/Youtube#154]
Any way to get the transcript of a video?

**Comment by alaouy** [comment]
@kylescousin Not directly via this package, but you can call this service by adjusting the v parameter to get the transcript of the video you are looking for with timestamps as well: [https://video.google.com/timedtext?lang=en&v=QPZ0pIK_wsc](https://video.google.com/timedtext?lang=en&v=QPZ0pIK_wsc)
