### ISSUE TITLE
For Lumen

### ISSUE THREAD

**Issue by andipahlevy** [alaouy/Youtube#155]
How to use this library for lumen?

**Comment by alaouy** [comment]
@andipahlevy I have been away from the PHP scene for a while now so I can't say for sure, it would be great if you can share your experience on integrating the package with lumen if you had the change to figure it out ;)

**Comment by bzbislawski** [comment]
@andipahlevy The same way as for laravel. All you have to do is `composer require` it. More info in readme.md
