### ISSUE TITLE
Casting for arrays in Youtube.php

### ISSUE THREAD

**Issue by vtellez** [alaouy/Youtube#156]
Hi,

I've recently updated to php 7.2.27 and I've found an error in src/Youtube.php

ErrorException: array_merge(): Argument #2 is not an array in /.../vendor/alaouy/youtube/src/Youtube.php:409

There are some lines with the same bug: **387, 409, 435,**

I've fixed it changing this line:

`$params = array_merge($params, $optionalParams);`

To this one:

`$params = array_merge((array)$params, (array)$optionalParams);`

Please, considere to update main core code to include this fix

**Comment by vtellez** [comment]
any good news?

**Comment by alaouy** [comment]
@vtellez I've been away from the PHP scene lately, all PRs for fixes or new features are welcome.
