### ISSUE TITLE
How to add more than 5 playlist using alaouy/youtube

### ISSUE THREAD

**Issue by Shubhon9** [alaouy/Youtube#161]
MustaphaAlaouy I am fetching playlist items for a playlistId using your package function,It is returning 50 videos with next pagetoken. Can you help me with params[] values to fetch result from next page token for any playlist, your above code of pagination is for fetching videos for any channel id, I want to fetch details with playlistId as params.

**Comment by alaouy** [comment]
@Shubhon9 The same pagination logic applies to the other resources.
