### ISSUE TITLE
Facade autocomplete is not working in phpstorm

### ISSUE THREAD

**Issue by anburocky3** [alaouy/Youtube#165]
I have imported the `use Alaouy\Youtube\Facades\Youtube;` but still I can't able to see the methods of YouTube class in your repository.

Check the image for more detail
![image](https://user-images.githubusercontent.com/15264938/105544860-6bdece80-5d21-11eb-88ce-e639e066b2b5.png)

Even if I search it, it's not suggesting.
![image](https://user-images.githubusercontent.com/15264938/105545023-a0eb2100-5d21-11eb-8153-db9b599f4e03.png)

**Comment by alaouy** [comment]
@anburocky3 Dod you resolve your issue?
