### ISSUE TITLE
searchChannelVideos & getVideoInfo

### ISSUE THREAD

**Issue by joewardpr** [alaouy/Youtube#166]
**searchChannelVideos** - Is there any factor that causes a YouTube channel to turn empty results here, beyond just not matching the query/keyword?

**getVideoInfo** - Not returning any date either for a single video ID or multiple.

**Comment by joewardpr** [comment]
I believe there may be something that allows (or is causing) some channels to not match the channel search, and also to prevent retrieval of video info if we get the video ID from some other method (like a channel list, instead of a channel search).

**Comment by alaouy** [comment]
@joewardpr Would be helpful to share few test cases of the bug you mentioned
