### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Google\Client' does not have a method 'getVideoInfo'

### ISSUE THREAD

**Issue by erxsto** [alaouy/Youtube#170]
Al momento de dirigirme a mi vista, me salta este error

**Comment by alaouy** [comment]
@erxsto Can you provide more details on how to reproduce the error?

**Comment by erxsto** [comment]
In my project, I installed Alaouy & Dawson, one to upload video and the other to view video details.
At the moment of uploading the video, it does not mark error. Then when I want to see the details, I get the error I mentioned. I add you how is my function:
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Dawson\Youtube\Facades\Youtube as YoutubeUpload;
use Alaouy\Youtube\Facades\Youtube;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = Youtube::getVideoInfo('YbIkHQVpDJ8');
        return view('content.videoindex', compact('videos'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('content/video');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        {
            $data = request()->validate([
                'title' => 'required|max:255',
                'description' => 'required',
                'video' => 'mimetypes:video/avi,video/mpeg,video/mp4'
            ]);
            $video = YoutubeUpload::upload($request->file('video')->getPathName(), [
                'title'       => $request->input('title'),
                'description' => $request->input('description')
            ]);
     
            return "Video uploaded successfully. Video ID is ". $video->getVideoId();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($video)
    {
        $video = YoutubeUpload::delete($video->getVideoId());
        return redirect('videoindex');
    }
}
`

**Comment by alaouy** [comment]
@erxsto Did you resolve your issue?
