### ISSUE TITLE
getVideoInfo with single string returns 'Object of class stdClass could not be converted to string'

### ISSUE THREAD

**Issue by kristiana-s** [alaouy/Youtube#172]
this `$video= Youtube::getVideoInfo('rie-hPVJ7Sw')` returns an error of `Object of class stdClass could not be converted to string`
whereas `$video= Youtube::getVideoInfo(['rie-hPVJ7Sw'])`  returns correct data, albeit in an array. Should the readme be updated or is there a genuine here?

**Comment by alaouy** [comment]
@kristiana-s Did you manage to resolve the issue?
