### ISSUE TITLE
"getPlaylistItemsByPlaylistId" by date order

### ISSUE THREAD

**Issue by benrolfe** [alaouy/Youtube#175]
Does anyone know how I can fetch the **latest** 5 videos from a YT playlist?

This is the PHP code I have so far:

`$results = Youtube::getPlaylistItemsByPlaylistId('PLo00OmIdkKM1Frqs8ZExOWpDtXOPwG6Ng', '', 5)`

But I don't know how to order by date.

**Comment by alaouy** [comment]
@benrolfe This is not supported on this method. It would be great if you can it to this package with a PR to provide this feature following the Youtube Data API: https://developers.google.com/youtube/v3/docs/search/list

<img width="867" alt="Screenshot 2021-11-14 at 17 36 54" src="https://user-images.githubusercontent.com/3118889/141689907-2e0e4165-5b9f-48af-b1e9-95f5e972d5f5.png">

Let me know if you need help or have question

**Comment by benrolfe** [comment]
It looks like the endpoint in question (https://www.googleapis.com/youtube/v3/playlistItems) doesn't allow you to order.

https://developers.google.com/youtube/v3/docs/playlistItems/list

**Comment by alaouy** [comment]
@benrolfe So the only solution is that you load all the items and order them in memory.
