### ISSUE TITLE
Checking if adding comments is allowed

### ISSUE THREAD

**Issue by GajdosGabriel** [alaouy/Youtube#176]
I use the getCommentThreadsByVideoId () function

The problem is that some videos have comments turned off, and then the cycle stops with an error

Exception
Error 403 The video identified by the <code> <a href="/youtube/v3/docs/commentThreads/list#videoId"> videoId </a> </code> parameter has disabled comments. : commentsDisabled
How can I avoid this by checking if adding comments is allowed?

Thank you for a great extension.

**Comment by alaouy** [comment]
@GajdosGabriel You will need to use a try catch block https://www.php.net/manual/en/language.exceptions.php in order to handle that case.
