### ISSUE TITLE
getChannelFromURL doesn't work with custom channel URLS

### ISSUE THREAD

**Issue by alasdairgallacher** [alaouy/Youtube#177]
Hi 

The `getChannelFromURL` function doesn't support the use of custom channel URLS.
Links like https://www.youtube.com/c/customname for example.

Do you know if there is any easy way around this, or does YouTube API not support queries via custom channel names? 

Thanks

**Comment by Slaver** [comment]
There are five variants of [custom channel URLs](https://support.google.com/youtube/answer/6180214?ref_topic=9257109) now:
1. `https://www.youtube.com/channel/UCK8sQmJBp8GCxrOtXWBpyEA`
2. `https://www.youtube.com/@Google`
3. `https://www.youtube.com/c/Google`
4. `https://www.youtube.com/user/Google`
and even
5. `https://www.youtube.com/Google`

I've created a [pull request](https://github.com/alaouy/Youtube/pull/183) with ability to use all of them.

**Comment by alaouy** [comment]
Thanks to @Slaver this issue is now resolved.
