### ISSUE TITLE
Exception Curl Error : getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by shykhamza** [alaouy/Youtube#182]
It was working perfectly. I just checked it and now I am having this exception in vendor/alaouy/youtube/src/Youtube.php:754

**Comment by alaouy** [comment]
@shykhamza Were you able to fix the issue? please provide more details on how to reproduce if possible

**Comment by shykhamza** [comment]
Hey! thanks for the reply! 

It was temporary error idk what was the reason. but it started working on its own.
