### ISSUE TITLE
Can't validate and get data from Clip and Playlist

### ISSUE THREAD

**Issue by micio86dev** [alaouy/Youtube#184]
If I try to validate a clip or playlist url isn't valid. If I force to get data from url, without validate it, got an exception:

exception: "ErrorException"
file: "/var/www/html/api.silenthillweb/source/vendor/alaouy/youtube/src/Youtube.php"
line: 782
message: "Undefined array key \"query\""

**Comment by alaouy** [comment]
@micio86dev Can you provide a code snippet example illustrating the issue?

**Comment by micio86dev** [comment]
> @micio86dev Can you provide a code snippet example illustrating the issue?

This is a clip URL: https://youtube.com/clip/Ugkxz0H9KblwVfnSfWGJiHAwlBPFCEiqRinB

**Comment by alaouy** [comment]
@micio86dev Please provide the `code` snippets that is throwing this exception, it will easier to debug and understand.
