### ISSUE TITLE
Order results searchChannelVideos

### ISSUE THREAD

**Issue by IgorKostine** [alaouy/Youtube#20]
Hi !
I have a problem with searchChannelVideos, i can not order the results.
Youtube::searchChannelVideos('video', '.....', $limit, 'date');
The method returns false to me.

'date' it's a valid value after the documentation..
https://developers.google.com/youtube/v3/docs/search/list#order

Thank you !

**Comment by alaouy** [comment]
@IgorKostine the order by date attribut option works correctly like this :
```php
$videos = Youtube::searchChannelVideos("app", "UCK8sQmJBp8GCxrOtXWBpyEA", 10, 'date');
```
it returns `false` only if there are no videos related to the query you passed.

**Comment by IgorKostine** [comment]
Thank you for your answer ! :)
But how can I have all the videos of an account from his channel id ?

**Comment by alaouy** [comment]
This is not explicitly supported with this package, maybe will add it later, for now you can just leave the query parameter empty and it will get you all user videos ordered by date :
```php
  $videos = Youtube::searchChannelVideos("", "UCK8sQmJBp8GCxrOtXWBpyEA", 50, 'date');
```

**Comment by IgorKostine** [comment]
It works !
Thank you very much :)
