### ISSUE TITLE
Paginating playlists for a channel by ID

### ISSUE THREAD

**Issue by hassankhan** [alaouy/Youtube#22]
Hi,

Currently it doesn't seem like there's any way to paginate playlists for a channel. The default returned is 5, and there's no easy way of doing it using the library, unless I'm missing something

Thanks

**Comment by alaouy** [comment]
@hassankhan Sorry for the late response, did you manage to paginate the channel playlists ?

**Comment by alaouy** [comment]
Closing this for now.

**Comment by hassankhan** [comment]
Hi sorry for the late reply, yes I did manage to in the end, can't remember how though, was a while ago!
