### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by vadimwe** [alaouy/Youtube#26]
"Fatal error: Call to undefined method Alaouy\Youtube\Facades\Youtube::parseVIdFromURL()"
"Fatal error: Call to undefined method Alaouy\Youtube\Facades\Youtube::parseVidFromURL()"

$videoId = Youtube::parseVidFromURL('https://www.youtube.com/watch?v=moSFlvxnbgk');

**Comment by alancpark** [comment]
I am getting a similar error. 

This is the command:
$video = Youtube::getVideoInfo('rie-hPVJ7Sw');

This is the error:
[Symfony\Component\Debug\Exception\FatalThrowableError]                               
Fatal error: Call to undefined method Alaouy\Youtube\Facades\Youtube::getVideoInfo()

**Comment by vadimwe** [comment]
@alaouy ?

**Comment by alaouy** [comment]
@vadimwe @alancpark sorry for the late response, what version of Laravel are you using?

**Comment by alancpark** [comment]
Thanks for the quick reply and the great package! I am using 5.2.

**Comment by alancpark** [comment]
@alaouy after your last commit, it's working for me now. Thanks!

**Comment by alaouy** [comment]
@alancpark @vadimwe Thanks for reporting this bug and sorry for any inconvenience 🙏

**Comment by vadimwe** [comment]
@alaouy Thanx for nice package and for fast fix!
