### ISSUE TITLE
Curl Error : SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by vkyeswa** [alaouy/Youtube#27]
Having this issue with laravel 5.2, how may i solve it

**Comment by vkyeswa** [comment]
solved it , it was my local settings issue

**Comment by git407** [comment]
потрудись сначала решить свою проблему самостоятельно говнюк

**Comment by alaouy** [comment]
@vkyeswa Glad you got to fix it ;)

**Comment by warmwhisky** [comment]
Can anyone shed any light on how to fix this locally. I'm on Laravel 5.2

**Comment by alaouy** [comment]
@warmwhisky please check issue #3, it has the solution for you problem.
