### ISSUE TITLE
tag for 5.2?

### ISSUE THREAD

**Issue by huglester** [alaouy/Youtube#28]
Hello,

1.2.x does not work in laravel 5.2
Master branch - works.

Maybe you could tag master for next version, with Laravel 5.2 support?

Thank you

**Comment by alaouy** [comment]
Hey @huglester,
Now you can use v1.2.1 which includes support for Laravel 5.2 and older versions 😉 
Good luck!

**Comment by huglester** [comment]
thank you btw:)
