### ISSUE TITLE
not working with Laravel 5

### ISSUE THREAD

**Issue by dbudimir** [alaouy/Youtube#3]
Hi 
tried library with Laravel 5(dev) and not working, getting class not found, is there any way that you could look what is problem???

Thx

**Comment by alaouy** [comment]
@dbudimir It's now updated to L5.

**Comment by hassankhan** [comment]
Hi, it doesn't work right now. There's quite a few fixes to get it running for L5, I can maybe do a PR later but can't guarantee it.

**Comment by alaouy** [comment]
#12

**Comment by thorstenHe** [comment]
Currently I get this error: 
BindingResolutionException in Container.php line 875: Unresolvable dependency resolving [Parameter #0 [ <required> $key ]] in class Alaouy\Youtube\Youtube
