### ISSUE TITLE
[Suggestion] Adding a check connection status function

### ISSUE THREAD

**Issue by jesusvazquez** [alaouy/Youtube#30]
Since this is an external integration with youtube using an api, would you find interesting adding a check conection status function in the library? 

Lets say that we're using a controller to handle this library, we have different API keys for different environments, I would say that a simple check in the tests or object initialization will come in handy as a good practice. I just did the check in my controller but then I thought that adding the function here might be a good idea.

Let me know what you think.

Cheers.

**Comment by alaouy** [comment]
@jesusvazquez If I correctly understood what you proposed, you want to add a test to see if the connection is Ok using the key, if that is the case the library throws an exception `Error 400 Bad Request : keyInvalid` if you provide an invalid key, if this is not convenient for your taste I would love to see a PR enhancing this ;)
