### ISSUE TITLE
Alaouy\Youtube\Youtube::getVideoInfo() should not be called statically

### ISSUE THREAD

**Issue by Vinlock** [alaouy/Youtube#32]
As the title states, i used your usage and it does not allow me to use it.

**Comment by alaouy** [comment]
@Vinlock Did you add `'Alaouy\Youtube\YoutubeServiceProvider',` to your providers list ?

**Comment by Vinlock** [comment]
```php
Alaouy\Youtube\YoutubeServiceProvider::class,
```
was added, yes.

I'm on Laravel 5.2

**Comment by alaouy** [comment]
I did the exact same thing and it worked, can you provide you code sample ? also you should check #31.

**Comment by Vinlock** [comment]
Oh i see! Alright.
