### ISSUE TITLE
Remove duplicate facade

### ISSUE THREAD

**Issue by hackel** [alaouy/Youtube#33]
`src/Alaouy/Youtube/YoutubeFacades.php` is identical to `src/Alaouy/Youtube/Facades/Youtube.php`.  In addition, the former is improperly named and namespaced.  This results in composer complaining:
```
Warning: Ambiguous class resolution, "Alaouy\Youtube\Facades\Youtube" was found in both "vendor/alaouy/youtube/src/Alaouy/Youtube/YoutubeFacades.php" and "vendor/alaouy/youtube/src/Alaouy/Youtube/Facades/Youtube.php", the first will be used.
````
I have no idea what YoutubeFacades.php is/was used for, but it clearly should be removed!

**Comment by alaouy** [comment]
@hackel Thanks for this!
