### ISSUE TITLE
parseVidFromURL shouldn't return exception

### ISSUE THREAD

**Issue by chaot1x** [alaouy/Youtube#34]
Youtube::parseVidFromURL(); should return false or null if url format is not valid instead of exception. Because if someone is giving invalid url page would just die.

**Comment by alaouy** [comment]
@chaot1x Using an exception there lets us send a message with the reason of the error, if you are getting the urls as a user input, you should definitely use a try catch block in case they enter an invalid url.

**Comment by chaot1x** [comment]
@alaouy Thanks totally forgot about try catch.
