### ISSUE TITLE
Static method calls in README

### ISSUE THREAD

**Issue by alexschwarz89** [alaouy/Youtube#35]
The methods mentioned in README can actually not called statically. But i'm kind of new to laravel, i followed all setup steps, is there another thing to do?

However, i managed to access it like `$youtube = App::make('youtube');`

**Comment by alaouy** [comment]
@alexschwarz89 Did you add `'Alaouy\Youtube\YoutubeServiceProvider'` to your providers list ?

**Comment by alexschwarz89** [comment]
@alaouy I added  `Alaouy\Youtube\YoutubeServiceProvider::class`to the providers array in config/app.php – it's not app/config/app.php as stated in readme and in this array always `::class` is used

**Comment by alaouy** [comment]
@alexschwarz89 Good to know that you got it fixed, I have been away from the Laravel scene for a while now, could care to make a pull request updating the readme file for this issue ?

**Comment by chaoraksa** [comment]
@alaouy I have been try to call Youtube::getChannelByName it produce error can't found my controller.
but i can call it in route. This is on version 5.

Any idea.

**Comment by alaouy** [comment]
@chaoraksa did you add the papckage provider to you providers array ?

**Comment by zaherballar** [comment]
Here is things needs to be updated in README file:
- Adding   Alaouy\Youtube\YoutubeServiceProvider::class   to the providers array in app/config/app.php 
- Adding 'Youtube'=> Alaouy\Youtube\Facades\Youtube::class   to the aliases array  in app/config/app.php 
- For usage exmple:
use Alaouy\Youtube\Facades\Youtube;
 $video = Youtube::getVideoInfo('rie-hPVJ7Sw');

**Comment by alaouy** [comment]
I amended the README file, thank you all 💯
