### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mooseh** [alaouy/Youtube#37]
Hi There Sorry i know this ist an issue but rather a general question

I love this Api its super easy to use with laravel, BUT Is there a way to sort the videos?
I looked in the youtubeapi docs with no such luck

this is what im looking to do

$YTvideos = Youtube::searchChannelVideos('{MY Channel}', '{MY KEY}', 40 , ['order' => 'date']);

**Comment by alaouy** [comment]
@mooseh Sorry for the late response, actually sorting is already supported in the current version of this library, you just had to look to the function params 
```php
public function searchChannelVideos($q, $channelId, $maxResults = 10, $order = null, $part = ['id', 'snippet'])
```
So you can do it like this :
```php
$YTvideos = Youtube::searchChannelVideos('channel', 'Id', 10, 'date')
```
And these are the values supported in the order param :

<img width="870" alt="capture d ecran 2016-09-19 a 19 49 24" src="https://cloud.githubusercontent.com/assets/3118889/18644549/c0eafe84-7ea1-11e6-8a80-72ef2458549d.png">

Ref: https://developers.google.com/youtube/v3/docs/search/list

Hope this was of help to you, and I think we should add this to the doc examples, if you can make a pull request for this I will happily merge it 😉

**Comment by alaouy** [comment]
Closing this for now, @mooseh feel free to reopen the issue if you think that his is still unresolved.
