### ISSUE TITLE
Curl Error : SSL: certificate verification failed (result: 5)

### ISSUE THREAD

**Issue by carauzs** [alaouy/Youtube#38]
Im having this problem using the latest version on Laravel 5.3 and osx 10.11.6.

Thanks in advance

**Comment by alaouy** [comment]
@carauzs This is not related to this library, but you need to update your local SSL_CERT_FILE variable, you can checkout this issue for more details https://github.com/Homebrew/legacy-homebrew/issues/32019#issuecomment-54100103
