### ISSUE TITLE
Any way to get time duration via your package ? ? 

### ISSUE THREAD

**Issue by imadsh** [alaouy/Youtube#40]
Hi , 
Any way to get time duration via your package ? ? 
i'm looking about this feature inside the playlist item   data

**Comment by alaouy** [comment]
@imadsh unfortunately the playlist [response](https://developers.google.com/youtube/v3/docs/playlistItems#resource) does not include the total duration of the playlist, The video duration is located in the video [resource](https://developers.google.com/youtube/v3/docs/videos#resource) and not in the playlistItem. And it require another lookup request.

**Comment by badrsh** [comment]
Hi @imadsh , you have to do it by your self , it's not include the playlist not because the owner of this package , 
google doesn't support that inside playlist items 
anyway , I had fix this before someday , I will try to see if i can commit it inside alaouy/Youtube  soon

**Comment by alaouy** [comment]
@badrsh Looking forward for you PR 🚀
