### ISSUE TITLE
no need for paramenter "q" in searchAdvanced()

### ISSUE THREAD

**Issue by fabnoe** [alaouy/Youtube#43]
This condition is not nesseccary and should be removed. Use case: Get a list of videos for a given channel id.

```
        if (empty($params) || !isset($params['q'])) {
            throw new \InvalidArgumentException('at least the Search query must be supplied');
        }
```

**Comment by alaouy** [comment]
@fabnoe can you please do it in a pull request and provide a test for this ?

**Comment by fabnoe** [comment]
Sorry. I am not that familiar with pull requests and tests.

**Comment by tylergets** [comment]
I just ran into this as well. I can provide a PR, but I'm not sure how to add a test removing a unneeded feature.

**Comment by alaouy** [comment]
@tylergets just make the PR I will handle the test for this one

**Comment by tylergets** [comment]
@alaouy please see PR #53

**Comment by tylergets** [comment]
@alaouy could you attach a tag to the latest PR then this issue should be able to be closed

**Comment by alaouy** [comment]
@tylergets the v1.2.3 is now available for download 🚀
