### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by maczdata** [alaouy/Youtube#46]
Do i need https to use this library

**Comment by alaouy** [comment]
@maczdata No you don't need https to use this package, if you experienced ssl errors on your development environment have a look at this issue to fix it #5

**Comment by maczdata** [comment]
on localhost, it worked, but on a live server, modifying my php.ini disables the entire site

**Comment by alaouy** [comment]
If your server was setup correctly there is no need to edit the php.ini file

**Comment by maczdata** [comment]
am just so confused. i var dumped the response on live server, it returned false

**Comment by maczdata** [comment]
its working now, thanks
