### ISSUE TITLE
Curl Error : SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mrduongdara** [alaouy/Youtube#47]
I got this message when I test on my local server. I dont know what cause this issue. Hope someone have solution for this.
Thank in advance
![capture](https://cloud.githubusercontent.com/assets/24785468/21489609/2d93154c-cc1f-11e6-9f6a-f4a524bd41aa.PNG)

**Comment by Maras0830** [comment]
@mrduongdara  issue #5 , it has the solution for you problem.

**Comment by mrduongdara** [comment]
@Maras0830  It worked. pretty awesome. Thank u very much.
