### ISSUE TITLE
Issue with curl

### ISSUE THREAD

**Issue by Kasendwa** [alaouy/Youtube#50]
Hello. Thanks for the good work on this package.

I installed it on the local server and it worked like charm. However, when I deployed to the live server, am getting an issue with curl as seen in attachment.

![error](https://cloud.githubusercontent.com/assets/3114425/22196490/758d1600-e15e-11e6-9749-02d4503ec51b.jpg)

Any idea where this could be coming from?

Thank you.

**Comment by alaouy** [comment]
@Kasendwa Be sure that the curl php extension is enabled on your server by removing the ; mark from the beginning of the following line in your php.ini file :
```
;extension=php_curl.dll
```
In a terminal type the following to install it and do not forgot to restart server.
```shell
sudo apt-get install php-curl
```
Or if you're using the old PHP5
```shell
sudo apt-get install php5-curl
```
