### ISSUE TITLE
5.4 Support

### ISSUE THREAD

**Issue by JoeDawson** [alaouy/Youtube#51]
Hello,

I recently updated one of my projects to Laravel 5.4 and came across an error when using your package.

> Unresolvable dependency resolving [Parameter #0 [ <required> $key ]] in class Alaouy\Youtube\Youtube

I'm not sure, but I think it may be related to the removal of the `share()` ([see here](https://github.com/alaouy/Youtube/blob/master/src/Alaouy/Youtube/YoutubeServiceProvider.php#L41)) method being removed in 5.4 and being replaced with the `singleton()` method.

I would love to submit a PR to fix this but I'm not sure how to test it :D

Hope someone can help :)

**Comment by alaouy** [comment]
@JoeDawson this is fixed in the PR #52, please give it a try and let us know ;)

**Comment by JoeDawson** [comment]
Thanks @kleiberd! 

All good @alaouy, any chance of a release? :)

**Comment by alaouy** [comment]
@JoeDawson You got it, v1.2.2 is now live ;)
