### ISSUE TITLE
php artisan vendor:publish not publish package config

### ISSUE THREAD

**Issue by messi89** [alaouy/Youtube#54]
Hi

I just install a fresh version of laravel 5.4.*

after installing the package I try to copy the config file to config dir with
`php artisan vendor:publish`

but the command doesn't publish the youtube.php file

**Comment by bzbislawski** [comment]
@messi89 
Try adding firstly to `app.php` those two lines that were mentioned in readme file. And then after:
`php artisan vendor:publish`

**Comment by alaouy** [comment]
@messerli90 Were you able to make it work on 5.4 ?

**Comment by bzbislawski** [comment]
@alaouy You called wrong guy

@messi89

**Comment by messi89** [comment]
@bzbislawski already done but publish not copy the file

anyway I do it manualy

**Comment by bzbislawski** [comment]
@messi89 Mind trying again (possibly on fresh Laravel project) because it worked for me if you invert the order?

**Comment by donmbelembe** [comment]
you have to set the service provider first then run the command
