### ISSUE TITLE
Status from channel by id

### ISSUE THREAD

**Issue by pigeaud** [alaouy/Youtube#55]
Apart from snippet, I need the status of the channel in the php object also. Is this possible?

Elmar

**Comment by alaouy** [comment]
@pigeaud  Hey, yes you can get the status as well by adding `status` to the `$part` parameter 
```php
$channel = Youtube::getChannelById('CHANNEL_ID', false, ['id', 'snippet', 'status'])
```

**Comment by pigeaud** [comment]
That gives an error, so I added it to Youtube.php
public function getChannelById($id, $optionalParams = false, $part = ['id', 'snippet', 'contentDetails', 'statistics', 'invideoPromotion'])

Then it works...

**Comment by alaouy** [comment]
@pigeaud changing the source of the package in the vendor directory is never a good idea, I just tried it and it works like this :
```php
  $channel = Youtube::getChannelById("UCK8sQmJBp8GCxrOtXWBpyEA", false, ['id', 'snippet', 'status']);
```
Be sure to add the other params if you need them : ` 'contentDetails', 'statistics', 'invideoPromotion' `

**Comment by pigeaud** [comment]
Well that's clear, but strangely I got an error... Solved it otherwise, and Youtube doesn't have it eligibility (verified channel) in status anymore...

Thanks
