### ISSUE TITLE
Showing data in a view??

### ISSUE THREAD

**Issue by tecnosoftware** [alaouy/Youtube#59]
Hello friends that I would like to have your help I am new to this laravel and I would like you to help me with an example of how to show the data obtained in $playlists within a view.

Thank you.

**Comment by alaouy** [comment]
Hey @tecnosoftware, So after you install the package like explained in the docs, in your controller you can get the playlists of the a channel by ID and pass it to your view like this:

```php
// Your controller#action

$playlists = Youtube::getPlaylistsByChannelId('UCk1SpWNzOs4MYmr0uICEntg');
return view('playlists', ['playlists' => $playlists])
```
You can access your playlists in the view like this :
```php
// playlists.blade.php

@foreach ($playlists['results'] as $playlist)
  {{ $playlist->id }}, {{ $playlist->snippet->title }} <br>
@endforeach
```
Hope this is clear enough for you to get started 😉

**Comment by tecnosoftware** [comment]
Thank  you!!!! @alaouy
