### ISSUE TITLE
Get brandingSettings

### ISSUE THREAD

**Issue by vtellez** [alaouy/Youtube#60]
Hello!

Just starting to use this package and I am wondering how can I get the channel's header image from an username account.

I've noticed that you can make a call like this one:
https://www.googleapis.com/youtube/v3/channels?part=brandingSettings&forUsername={USERNAME}&key={YOUR_API_KEY}

But I would like make it using this package methods. Is there any way to do it?

Thanks in advance

**Comment by alaouy** [comment]
@vtellez Yes you can get the channel's banner image using this package like this :
```php
$channel = Youtube::getChannelByName('google', false, ['id', 'snippet', 'contentDetails', 'statistics', 'invideoPromotion', 'brandingSettings']);
print_r($channel->brandingSettings->image->bannerImageUrl);
```

**Comment by vtellez** [comment]
Thank you very Much!!

Regards!
