### ISSUE TITLE
hi，method “givevideoinfo” not found in .....

### ISSUE THREAD

**Issue by ysk99** [alaouy/Youtube#71]
i do what you said in my project,and own a api from google , but in the controller
```
<?php
namespace App\Http\Controllers;
use Alaouy\Youtube\Facades\Youtube;



class ConvtestController extends Controller
{

    public function api()
    {
        $video = Youtube::getVideoInfo('rie-hPVJ7Sw');
    }


}
```
method “givevideoinfo” not found in  Alaouy\Youtube\Facades\Youtube;

thanks

**Comment by bzbislawski** [comment]
@ysk99 Did you read README.md? You probably did not add entries to `/config/app.php`

**Comment by ysk99** [comment]
@bzbislawski i found is the ide's fault , i put to my vps , its done well . thanks
