### ISSUE TITLE
google key missing when scheduling a job

### ISSUE THREAD

**Issue by al6s1976** [alaouy/Youtube#73]
I don't really know if this a problem with the package or with laravel

I use the facade in a job that is pushed to a queue. It fails returning an exception 

```Google API key is Required, please visit https://console.developers.google.com/ in public_html/vendor/alaouy/youtube/src/Youtube.php:43 ```

They the installation and key are correct cause if i don't use a queue everything works fine!

**Comment by alaouy** [comment]
@al6s1976 I'm really not sure about that, it might be and issue with the queue scheduler not having access to the package's config file, can you confim that ?

**Comment by al6s1976** [comment]
Unfortunately i cannot 

I restarted the server (restarting apache didn"t help) and now everything is in order.  But still i'm puzzled as to what caused it.

**Comment by alaouy** [comment]
@al6s1976 I see, glad that you got is fixed at least !
