### ISSUE TITLE
listChannelVideo's return other object than getVideoInfo does

### ISSUE THREAD

**Issue by Cannonb4ll** [alaouy/Youtube#75]
I noticed that when I list all video's from a channel, I get a list of objects back:

![image](http://screenshot.serverbuilds.nl/0r3Q3s1Z1f0n/Image%202017-08-14%20at%2010.19.56%20AM.png)

But when I request a single video, I get far more detailed information for that specific video:

![image2](http://screenshot.serverbuilds.nl/3h1Z250Q2h1y/Image%202017-08-14%20at%2010.20.56%20AM.png)

Wouldn't it be better if the `listChannelVideo` method would return more information as well, might even return the same object as `getVideoInfo` to keep code responsibility?

**Comment by alaouy** [comment]
@Cannonb4ll The reason behind the decision is that the `listChannelVideos` function fetches a list of videos and if we include all the information for each video it will make the objects returned a lot heavier and might cause performance issues in your app.
If you still want to have the missing info for each video you might call the function with the parts you desire to include like this:
```php
$videos = Youtube::listChannelVideos($channelId, 10, null, ['id', 'snippet', 'contentDetails', 'player', 'statistics', 'status']);
```

**Comment by tahirafridi** [comment]
It is working only with default 2 parameters, if I input contentDetails or other params it says Error 400 contentDetails : unknownPart

Could you please test it and let us know if its working.

Thanks!
