### ISSUE TITLE
Lack of docs for paginating the playlist results

### ISSUE THREAD

**Issue by hassanazimi** [alaouy/Youtube#77]
I have this:
```php
$courses   = Youtube::getPlaylistsByChannelId($channelId);
```

There is no docs about how to paginate the results as I only see 5 results and nextPageToken value.
Help?

**Comment by alaouy** [comment]
@hassanazimi you can use the same approach of the search pagination, please give it a try and let me know how it goes

**Comment by hassanazimi** [comment]
@alaouy It worked but I must accept it's a bit confusing. I use Laravel so I implemented like this for anyone else who wants to use pagination because I think it's the only YouTube API great project for Laravel:

```php
$channelId = 'UCW0ojdh94N5-bFiidIepdDg';
$params    = ['maxResults' => 50];
	
if (request('prevPageToken')) {
	$params['pageToken'] = request('prevPageToken');
}

if (request('nextPageToken')) {
	$params['pageToken'] = request('nextPageToken');
}

$courses = Youtube::getPlaylistsByChannelId($channelId, $params);
```
