### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $key ]]

### ISSUE THREAD

**Issue by poppabear8883** [alaouy/Youtube#78]
Should be able to resolve dependency from container.

Facade works Great ... But to follow better practice you should not use Facades in Repositories.

**Error:**
> Unresolvable dependency resolving [Parameter #0 [ <required> $key ]] in class Alaouy\\Youtube\\Youtube

**Code:**
```php
use Alaouy\Youtube\Youtube;
...
private $model;
private $youtube;

public function __construct(Song $model, Youtube $youtube)
{
    $this->model = $model;
    $this->youtube = $youtube;
}
...
$video = $this->youtube->getVideoInfo($video_id);
```
**Config:**
```php
return [
    'key' => env('YOUTUBE_KEY', '')
];
```

***.env***
> YOUTUBE_KEY=***SECRET CODE***

**Comment by poppabear8883** [comment]
Work Around:

**App\Providers\AppServiceProvider.php:**
```php
public function register()
{
     $this->app->when(Youtube::class)
         ->needs('$key')
         ->give(config('youtube.key'));
}
```

**Comment by alaouy** [comment]
@poppabear8883 Thanks for this issue, I've been away from the Laravel scene for a while now, if you can provide the solution you proposed in a PR without breaking the existing implementation of the Facades approach and adding support for the container dependency approach that would be great.

**Comment by poppabear8883** [comment]
@alaouy An easy solution is to apply the work around to your `YoutubeServiceProvider.php` class in the `register()` method. **Untested** (*should work in theory*)

```php
public function register()
{
    $this->app->bind('youtube', function () {
        return new Youtube(config('youtube.key'));
    });
    
    $this->app->when(Youtube::class)
     ->needs('$key')
     ->give(config('youtube.key'));
}
```
