### ISSUE TITLE
Google API key is missing

### ISSUE THREAD

**Issue by anish000kumar** [alaouy/Youtube#82]
The package works fine on localhost but on server I am getting the key missing error while trying the API in console with artisan-
```
dev@server1: php artisan tinker
Psy Shell v0.7.2 (PHP 7.1.7-1+ubuntu16.10.1+deb.sury.org+1 — cli) by Justin Hileman
>>> \Youtube::getVideoInfo('rie-hPVJ7Sw');
Exception with message 'Google API key is Required, please visit https://console.developers.google.com/'
>>>
```
I have ensured to check that there exists youtube.php file in config folder with a valid API key. Also fetching config('youtube.KEY') in artisan console provides me the valid youtube api key as well. So it cannot be an  issue with config cache for sure.

**Comment by amainz** [comment]
Hi,

I had the same issue today. In a former environment with php 5 it worked.
Seems that with php7.1 case sensitive is an issue.
I changed config/youtube.php the "KEY" to "key" and did a "php artisan config:cache".

Works now.
