### ISSUE TITLE
again Non-static method Alaouy\Youtube\Youtube::getVideoInfo() should not be called statically

### ISSUE THREAD

**Issue by vlahde** [alaouy/Youtube#87]
Hi and sorry to bring this one up again but I get this error on Laravel 5.3

"Non-static method Alaouy\Youtube\Youtube::getVideoInfo() should not be called statically" 

I noticed that there was two issues already about the same thing. I double and triple checked that I have added the both lines from read me to config/app.php to providers and aliases array. I have used optimize class loader but still I get the same error. I cant figure out what is the problem

**Comment by svenluijten** [comment]
Looks like you're importing `Alaouy\Youtube\Youtube` at the top, while this should be either `Youtube` or `Alaouy\Youtube\Facades\Youtube`:

```php
// Wrong:
use Alaouy\Youtube\Youtube;

// Right:
use Alaouy\Youtube\Facades\Youtube;
```
