### ISSUE TITLE
How can I retrieve a channels latest uploads?

### ISSUE THREAD

**Issue by JoeDawson** [alaouy/Youtube#89]
Hello,

Is it possible to fetch a channels latest uploads? I'm trying to use `listChannelVideos` but it doesn't appear to return the latest videos.

Am I doing something wrong?

Thanks in advance.

**Comment by alaouy** [comment]
@JoeDawson You can pass 'date' in the order parameter of `listChannelVideos` [signature here](https://github.com/alaouy/Youtube/blob/master/src/Youtube.php#L212)
Like this :
```php
$videos = Youtube::listChannelVideos('channelId', 10, 'date')
```

**Comment by JoeDawson** [comment]
Thanks @alaouy, that works perfectly.
