### ISSUE TITLE
Package doesn't publish any files

### ISSUE THREAD

**Issue by Jase2k16** [alaouy/Youtube#90]
When running the artisan command to publish the assets, nothing is published. It appears the package installation is not completing according to the documentation.

**Comment by alaouy** [comment]
@Jase2k16 This package doesn't have any assets, the only file that is published is the config file where you can set your API key, is that's the issue ?

**Comment by Jase2k16** [comment]
Sorry, didn't explain very clearly. The configuration file didn't copy over to the config directory. I meant the configuration file didn't publish.

**Comment by alaouy** [comment]
@Jase2k16 sorry to hear that, can you please do it on a fresh Laravel installation and let us know how it goes ? thanks

**Comment by Jase2k16** [comment]
To be honest it wasn't too much of an issue and I just manually copied it over and there were no further issues. I shall try this on a new installation of Laravel.

**Comment by acidjazz** [comment]
Confirmed issue, no config file, would also love auto discovery for 5.5

**Comment by bzbislawski** [comment]
@Jase2k16 Config does not publish because you have not added YoutubeProvider to the list. Auto-discovery should fix this problem. It's been already added in #76 but need version bump.
