### ISSUE TITLE
For Lumen 5.4 Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by bakatov82** [alaouy/Youtube#91]
when used in lumen error appears Class 'Illuminate\Foundation\Application' not found

**Comment by alaouy** [comment]
This is not related to this package, you can have a look on this feed you will find a solution to your issue there : https://laracasts.com/discuss/channels/general-discussion/fatal-error-class-illuminatefoundationapplication-not-found-in-pathtoprojectbootstrapappphp-on-line-14?page=0
