### ISSUE TITLE
Support for Auto-Discovery for Laravel 5.5

### ISSUE THREAD

**Issue by acidjazz** [alaouy/Youtube#93]
example from laravel-debugbar's composer.json

```js
 "extra": {
        "branch-alias": {
            "dev-master": "3.2-dev"
        },
        "laravel": {
            "providers": [
                "Barryvdh\\Debugbar\\ServiceProvider"
            ],
            "aliases": {
                "Debugbar": "Barryvdh\\Debugbar\\Facade"
            }
        }
```

**Comment by acidjazz** [comment]
BTW I do see that you added this in your `composer.json`, for some reason it just doesn't get picked up.

**Comment by alaouy** [comment]
@acidjazz indeed we do support auto-discovery for laravel, not sure why it doesn't pick it up automatically, I've been away from the Laravel scene for a while, where you able to debug it on your end ?

**Comment by acidjazz** [comment]
@alaouy i think you just need to issue a release, it's sitting in master I think?

**Comment by bzbislawski** [comment]
@alaouy Please tag the latest commit so people can start using auto-discovery.

**Comment by alaouy** [comment]
@bzbislawski @acidjazz A new release v2.2.0 is out, please try it out and let me know how it goes

**Comment by bzbislawski** [comment]
@alaouy Tested, works well. Also, would appreciate higher permissions for the repo. Thanks! :)

**Comment by acidjazz** [comment]
@alaouy @bzbislawski I'm happy to contribute and help get releases/PR's tested/out as well.

**Comment by alaouy** [comment]
@bzbislawski Thanks for the feedback and the help in the past months, I've sent you and invite to the repo ;)

**Comment by bzbislawski** [comment]
Great! Let me do the honours and close this issues as it's been resolved now.
