### ISSUE TITLE
Error 400 Bad Request: KeyInvalid

### ISSUE THREAD

**Issue by jcadima** [alaouy/Youtube#99]
1) Installed the package:
composer require alaouy/youtube

2) added to the service and facade arrays:
Alaouy\Youtube\YoutubeServiceProvider::class,
'Youtube' => Alaouy\Youtube\Facades\Youtube::class,

3) Set the google API key

4) ran vendor publish
php artisan vendor:publish --provider="Alaouy\Youtube\YoutubeServiceProvider"

I'm running the most basic test in a welcome controller:
use Alaouy\Youtube\Facades\Youtube;

```php
namespace App\Http\Controllers;

use App\User;
use Charts;
use Alaouy\Youtube\Facades\Youtube;
use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {

      $video = Youtube::getVideoInfo('XhosGrFH5Vs');
      dd( $video) ;
    }
}
```

Always get this error:

```
Error 400 Bad Request : keyInvalid
/Applications/XAMPP/xamppfiles/htdocs/laratubedemo/vendor/alaouy/youtube/src/Youtube.php#546
```

**Comment by alaouy** [comment]
@jcadima Sorry for the late response, were you able to solve the issue ?

**Comment by jcadima** [comment]
@alaouy ,
Yes, i reinstalled laravel and installed first the charts package and then the others used by my application and didnt have that issue anymore, i dont know what might have been causing a keyInvalid error
